<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_katalon</name>
   <tag></tag>
   <elementGuidId>edf4de6c-5c49-4570-bd5d-8154bf7f5f6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(4) > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[4]/div[2]/div/div[4]/div[2]/div[3]/div[2]/table/tbody/tr/td[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;katalon測試員工&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>69c11408-d728-4f8c-b24e-92c02947a02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>katalon測試員工</value>
      <webElementGuid>db8216c1-aaf5-4f91-bb97-f25c52a784b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;_background_ksi1r_1&quot;]/div[@class=&quot;_content_ksi1r_101&quot;]/div[@class=&quot;_content-div_ksi1r_108&quot;]/div[@class=&quot;_index-temp_15g28_1&quot;]/div[2]/div[@class=&quot;table-content&quot;]/div[2]/table[1]/tbody[1]/tr[1]/td[4]/div[1]</value>
      <webElementGuid>00414fdc-77fb-47bd-a3b6-af402970eb3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div[2]/div/div[4]/div[2]/div[3]/div[2]/table/tbody/tr/td[4]/div</value>
      <webElementGuid>b714eef6-b6a8-4672-84e0-fb59b1866f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='半半1'])[1]/preceding::div[1]</value>
      <webElementGuid>0d3fbfa0-2d54-41e5-800a-ba13ccc4118b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='重設密碼'])[1]/preceding::div[2]</value>
      <webElementGuid>6b6373e4-d484-452d-8981-b6f3bf71ce09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='katalon測試員工']/parent::*</value>
      <webElementGuid>fcc63113-f3f7-4aec-b200-ebf757b9b7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div</value>
      <webElementGuid>c7beeb38-cf4f-4188-8bbb-f24a056bd957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'katalon測試員工' or . = 'katalon測試員工')]</value>
      <webElementGuid>d55ad6bb-32a7-4e81-a4f1-190bfaf4a444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
