<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__7e35d6f4-3989-482d-aa7f-e9870020e241</name>
   <tag></tag>
   <elementGuidId>bead4478-df53-456c-9ddf-bfba95ef7739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#7e35d6f4-3989-482d-aa7f-e9870020e241</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='7e35d6f4-3989-482d-aa7f-e9870020e241']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;請輸入密碼&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf67be80-2d55-4866-83e0-56195a26f592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7e35d6f4-3989-482d-aa7f-e9870020e241</value>
      <webElementGuid>79e4ed92-8f9c-4412-bc08-a027e9f8e315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8dbe352b-1f58-4ac9-a0ca-326fe35fe35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>請輸入密碼</value>
      <webElementGuid>8d5d24fc-69d2-4063-aee0-eb83396879d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;7e35d6f4-3989-482d-aa7f-e9870020e241&quot;)</value>
      <webElementGuid>8cfb9ecc-12b3-43b9-a3e6-2499ca99d88f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='7e35d6f4-3989-482d-aa7f-e9870020e241']</value>
      <webElementGuid>b314b66f-2c8a-44ff-9e24-02ddb0e9819f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[4]/div/div/div/div[2]/input</value>
      <webElementGuid>815422a6-de1e-4f6f-83c4-199efe2c62b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4bc539c3-7aec-4555-b382-c5032dbc4526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '7e35d6f4-3989-482d-aa7f-e9870020e241' and @type = 'password' and @placeholder = '請輸入密碼']</value>
      <webElementGuid>2dfddab5-3d52-497c-9f5b-017cc6419022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
